name: Build and release library as an artifact

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
      publish:
        description: 'Publish: If want ignore'
        required: false
      artifact-pack:
        description: 'artifact-pack: If want ignore'
        required: false

jobs:
  build-packages:
    runs-on: 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build library
        run: |
          for file in docker/Dockerfile-build.*
          do
          TARGET=$(echo "$file" | sed 's/Dockerfile-build.//')
          docker run --rm --mount  $(docker build -q -f docker/"$file")


          
